name: internal_network
description: internal_network project.
version: 0.0.1+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ">=6.1.3"
  dio: ">=5.8.0+1"
  pretty_dio_logger: ^1.4.0
  mqtt_client: ">=10.7.0"
  
  internal_core: 
    path: ../core

dev_dependencies:
  flutter_lints: ">=5.0.0"

jsonToDart: 
  typeChecking: false
  nullValueDataType: dynamic #default: dynamic
  nullSafety: true #default: false
  copyWithMethod: false
  mergeArrayApproach: false #default: true
