name: internal_core
description: Private widgets package.
version: 0.1.0+4

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
    
  intl: ">=0.18.1" 
  google_fonts: ">=6.2.1"
  flutter_staggered_animations: ">=1.1.1"
  flutter_svg: ">=2.0.10+1"
  lottie: ">=3.1.0"
  cached_network_image: ">=3.3.1"
  octo_image: ">=2.0.0"
  dash_flags: ">=0.1.1"
  logger: ">=2.2.0"
  libphonenumber_plugin: ^0.3.3
  equatable: ">=2.0.5"
  collection: ">=1.18.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=3.0.2"

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 
    - assets/images/png/
