name: internal_core
description: Private widgets package.
version: 0.1.0+4

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
    
  intl: ">=0.20.2" 
  google_fonts: ">=6.2.1"
  flutter_staggered_animations: ">=1.1.1"
  flutter_svg: ">=2.0.17"
  lottie: ">=3.3.1"
  cached_network_image: ">=3.4.1"
  octo_image: ">=2.1.0"
  dash_flags: ">=0.1.1"
  logger: ">=2.5.0"
  libphonenumber_plugin: ^0.3.3
  equatable: ">=2.0.7"
  collection: ">=1.19.1"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=5.0.0"

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 
    - assets/images/png/
